In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\HP\Downloads\Fish.csv")

In [3]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
data['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data['Species']=l.fit_transform(data['Species'])

In [6]:
Species=pd.DataFrame(data[['Species']])
Species

Species
0          0
1          0
2          0
3          0
4          0
..       ...
154        5
155        5
156        5
157        5
158        5

[159 rows x 1 columns]

In [7]:
Species=pd.DataFrame(data[['Species']])
Species

Species
0          0
1          0
2          0
3          0
4          0
..       ...
154        5
155        5
156        5
157        5
158        5

[159 rows x 1 columns]

In [8]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0          0   242.0     23.2     25.4     30.0  11.5200  4.0200
1          0   290.0     24.0     26.3     31.2  12.4800  4.3056
2          0   340.0     23.9     26.5     31.1  12.3778  4.6961
3          0   363.0     26.3     29.0     33.5  12.7300  4.4555
4          0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154        5    12.2     11.5     12.2     13.4   2.0904  1.3936
155        5    13.4     11.7     12.4     13.5   2.4300  1.2690
156        5    12.2     12.1     13.0     13.8   2.2770  1.2558
157        5    19.7     13.2     14.3     15.2   2.8728  2.0672
158        5    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [9]:
cl=data[['Weight']]
fv=data[['Species','Length1','Length2','Length3','Height','Width']]

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(fv,cl,train_size=0.7)

In [11]:
lr=LinearRegression()

In [12]:
model=lr.fit(x_train,y_train)

In [13]:
# y=wx+wo

In [14]:
lr.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

In [15]:
predi=model.predict(x_test)

In [16]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [17]:
mean_squared_error(y_test,predi)

12315.12548564487

In [18]:
mean_absolute_error(y_test,predi)

85.66842437584609

In [19]:
r2_score(y_test,predi)

0.8693206201970667

In [20]:
model.coef_

array([[ 41.86256822, -28.26001565, 104.06355172, -50.85929849,
         50.56424088, -20.77180306]])

In [21]:
model.intercept_

array([-681.35398621])

In [22]:
y=(9491*1.1)+26740
y

37180.1

In [23]:
len(model.predict(fv))

159

In [24]:
model.predict(fv).reshape(len(model.predict(fv)))

array([ 2.79446316e+02,  3.32073586e+02,  3.47519174e+02,  4.40598121e+02,
        3.80961427e+02,  4.72591471e+02,  5.04650974e+02,  4.23729862e+02,
        4.82947434e+02,  4.83221549e+02,  5.16089285e+02,  5.19118071e+02,
        5.27995240e+02,  5.16081398e+02,  5.74620349e+02,  5.90573395e+02,
        5.87345170e+02,  5.82922937e+02,  6.52204086e+02,  5.73343790e+02,
        6.12598553e+02,  6.72909132e+02,  6.74750250e+02,  6.52128708e+02,
        7.04669183e+02,  6.83551621e+02,  6.92484020e+02,  7.43793838e+02,
        7.47516404e+02,  8.77070886e+02,  8.74126079e+02,  8.81890621e+02,
        9.10305966e+02,  9.96016516e+02,  9.05205788e+02, -7.24929011e+01,
        9.06116312e+01,  9.13200138e+01,  1.21202849e+02,  1.52719346e+02,
        1.80661591e+02,  1.77332325e+02,  1.58572751e+02,  1.58279911e+02,
        2.22027065e+02,  2.37739640e+02,  2.24712942e+02,  2.04435698e+02,
        2.79835462e+02,  2.15760107e+02,  2.32298398e+02,  2.99780879e+02,
        3.83858749e+02,  

In [25]:
import joblib

In [27]:
joblib.dump(model,r"C:\Users\HP\Desktop\ML SPECIAL\fish.joblib")

['C:\\Users\\HP\\Desktop\\ML SPECIAL\\fish.joblib']